# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - sourceline: 'ppa:hvr/ghc'
          key_url: 'https://packagecloud.io/gpg.key'
        packages:
        - ghc-7.8.4
  - env: GHCVER=7.10.3 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - sourceline: 'ppa:hvr/ghc'
          key_url: 'https://packagecloud.io/gpg.key'
        packages:
        - ghc-7.10.3
  - env: GHCVER=8.2.1 STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - sourceline: 'ppa:hvr/ghc'
          key_url: 'https://packagecloud.io/gpg.key'
        packages:
        - ghc-head
  - env: GHCVER=head STACK_YAML=stack.yaml
    addons:
      apt:
        sources:
        - sourceline: 'ppa:hvr/ghc'
          key_url: 'https://packagecloud.io/gpg.key'
        packages:
        - ghc-head
  allow_failures:
    - env: GHCVER=head STACK_YAML=stack-head.yaml

before_install:
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

# This line does all of the work: installs GHC if necessary, build the library,
# executables, and test suites, and runs the test suites. --no-terminal works
# around some quirks in Travis's terminal implementation.
script:
  - stack --no-terminal --install-ghc test

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
