name: &name hlint-test
version: 0.1.0.0
synopsis: Run hlint in test suite
description: >
    Allows you to write small  hlint test runner; so you will not
    forget to run hlint before pushing to master.
homepage: https://github.com/Siprj/hlint-test#readme
license: BSD3
author: Tomáš Janoušek <tomi@nomi.cz>, Jan Šipr <sipr.jan@gmail.com>
maintainer: Jan Šipr <sipr.jan@gmail.com>
copyright: 2017  Tomáš Janoušek, Jan Šipr
category: test
github: Siprj/hlint-test
extra-source-files:
  - README.md
  - CHANGES.md

dependencies:
  - base >= 4.7 && < 5
  - hlint >= 2.0

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-missing-import-lists
  - -fwarn-implicit-prelude

flags:
  pedantic:
    description: "Pass additional warning flags and -Werror to GHC."
    default: false
    manual: true

when:
  - condition: flag(pedantic)
    ghc-options:
      - -Werror

library:
  source-dirs: src

executables:
  hlint-test:
    source-dirs: driver
    main: hlint-test.hs
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - *name

tests:
  hlint:
    source-dirs: test
    main: hlint.hs
    ghc-options:
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - hlint-test
